### ISSUE TITLE
Proper usage of bin/go

### ISSUE THREAD

**Issue by zachgarwood** [kherge-archive/php-go#10]
Perhaps I'm misunderstanding something fundamental about how to properly use Go, but in order to be able to run the binary from the command line, I had to add the following to [line 3](https://github.com/herrera-io/php-go/blob/master/bin/go#L3) of `bin/go`:

``` php
require dirname(dirname(dirname(__DIR__))) . '/autoload.php';
```

What am I missing?

**Comment by ghost** [comment]
Lines 6-10 handle `require`ing the autoloader after it has been installed using Composer, or if you are using the phar.

Are you seeing an error message?

**Comment by zachgarwood** [comment]
Here's a quick recreation of what I was trying to do yesterday:
1. Created a new Composer file:

``` json
{
    "require-dev": {
        "herrera-io/go": "*"
    }
}
```
1. Ran `composer install`
2. Created a Gofile:

``` php
<?php

use Herrera\Go\Go;
use Symfony\Component\Console\Input\InputInterface as In;
use Symfony\Component\Console\Output\OutputInterface as Out;

task(
    'test',
    'This is a test task',
    function(Go $go, In $in, Out $out) {

    }
);
```
1. Ran `vendor/bin/go test`:

```
PHP Fatal error:  Class 'Herrera\Go\Go' not found in /[blah/blah/blah]/gotest/vendor/herrera-io/go/bin/go on line 12
PHP Stack trace:
PHP   1. {main}() /[blah/blah/blah]/gotest/vendor/herrera-io/go/bin/go:0
```

I feel as though I'm missing something that's really obvious here, but after reading through your documentation several times, I'm not able to determine what that is.

**Comment by ghost** [comment]
Unfortunately I'm not able to replicate the problem you're having.

```
[vm] 09:39:19 ~ $ cd Testing/
[vm] 09:39:21 Testing $ cd php
[vm] 09:39:23 php $ mkdir go
[vm] 09:39:24 php $ cd go
[vm] 09:39:25 go $ composer require herrera-io/go=2.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing herrera-io/service-container (1.1.0)
    Loading from cache

  - Installing kherge/version (1.0.1)
    Loading from cache

  - Installing seld/jsonlint (1.1.2)
    Loading from cache

  - Installing justinrainbow/json-schema (1.3.5)
    Loading from cache

  - Installing herrera-io/json (1.0.3)
    Loading from cache

  - Installing herrera-io/phar-update (1.0.3)
    Loading from cache

  - Installing herrera-io/service-update (1.0.3)
    Loading from cache

  - Installing symfony/console (v2.4.1)
    Loading from cache

  - Installing herrera-io/cli-app (2.0.0)
    Loading from cache

  - Installing herrera-io/go (2.2.1)
    Loading from cache

symfony/console suggests installing symfony/event-dispatcher ()
Writing lock file
Generating autoload files
[vm] 09:40:41 go $ vi Gofile
[vm] 09:40:47 go $ vendor/bin/go test
[vm] 09:40:54 go $ 
```

Are you sure that Go was installed? I know that I've had problems with Composer not installing all packages when the install process fails somewhere in the middle and is resumed (after having made some changes to `composer.json`).

**Comment by zachgarwood** [comment]
Thanks for taking the time to look into this. I'll look at my setup a little closer. Maybe it does have something to do with Composer.

**Comment by ghost** [comment]
I'll close the ticket for now. If you come across any new information, I will re-open the issue for you.
