### ISSUE TITLE
There is another Pake project

### ISSUE THREAD

**Issue by indeyets** [kherge-archive/php-go#4]
Hi.

"Pake" is a name of another php automation tool https://github.com/indeyets/pake which dates back to 2005. I think it would be better if you invent some other name for the project, as your users are [already coming to my github](https://github.com/indeyets/pake/issues/30) :)

**Comment by ghost** [comment]
Damn, sorry about that!

When I named my project I searched Google to make sure it didn't collide with anyone else's project.

I will be renaming mine.

**Comment by ghost** [comment]
The project has been renamed to [Go](https://github.com/herrera-io/php-go).

Again, I'm sorry about this, @indeyets.
