### ISSUE TITLE
go doesn't find autoload.php

### ISSUE THREAD

**Issue by deweller** [kherge-archive/php-go#5]
When I have go in a directory separate from my project, it does not find composer.json and won't run.

```
$ cd /some/new/project/directory
$ /Volumes/DocsHD/Development/tools/php-go/vendor/bin/go
Unable to load Go.
```

Should this work?

**Comment by ghost** [comment]
Is Go installed as a Composer dependency?

Or is it a `git clone` and `composer install` setup for Go?

**Comment by deweller** [comment]
Yes.  I went into a new directory and did:

```
composer require 'herrera-io/go=1.*'
```

**Comment by ghost** [comment]
I am able to reproduce the issue.

I will try and fix this today.

**Comment by deweller** [comment]
So, to be clear, I did this:

```
# to install go
$ cd /some/tools/directory
$ composer require 'herrera-io/go=1.*'

# then, to use go
$ cd /some/project/directory
$ /some/tools/directory/vendor/bin/go
Unable to load Go.
```

**Comment by ghost** [comment]
Could you please give `dev-master` a try?

A quick test on my end shows that it is working, but I want to make sure it works for you before I release a tagged version.

**EDIT:** I just wanted that clarify that the new commit I just pushed is working, fixing the issue you are experiencing.

**Comment by deweller** [comment]
It does work now when I run go referenced directly from the installed directory.

But I encountered another related problem.  When I tried to create a global symlink, say to `/usr/local/bin/go`, then I get this error:

`The composer.json file could not be found.`

Is it possible to make it work without relying on `$_SERVER['argv'][0]`?  `$_SERVER['argv'][0]` references a symlink and not the real file path.

**Comment by ghost** [comment]
The Go run file has to do the following:
- Run from a
  - Composer installation
  - cloned repository
  - Phar
- Load the relevant Composer autoloader

From what I have been able to test, using `$_SERVER['argv'][0]` has been the best option.

The new commit (as seen above) should now also address your use case.

Could you please give `dev-master` one more try?

**Comment by deweller** [comment]
Thanks.  Works great for me now.

I didn't remember that `realpath` resolves symlinks.  Nice.

**Comment by ghost** [comment]
Awesome, I'm glad that worked!

I will be releasing a tagged version now (1.3.3).

An updated Phar will soon be available too.
